module.exports = {
  API_BASE_URL: 'https://localhost:3001/api/',
  HTTP_URL: 'http://localhost:3002/api',
  AUTHENTICATION: 'auth',
  EXAM_REGULATIONS: 'exam-regulations',
  MAJOR: 'major',
  MODULE: 'module',
  DOCENT: 'docent',
  ER_GROUP: 'er-group',
  MODULE_ER_GROUP: 'module-er-group',
  COURSE: 'course',
  DOCENT_COURSE: 'docent-course',
  USER: 'user',
  COMPULSORY_MODULE: 'compulsory-module',
  PERMISSION: 'permission',
};
